#!/usr/bin/env bash

set -e

if [ ! -d $HOME/.mozilla/firefox/*.gnome ]; then
    firefox -CreateProfile gnome
    cp -r $HOME/.mozilla/firefox/base/* $HOME/.mozilla/firefox/*.gnome/
fi

firefox -P gnome
